"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var express_1 = tslib_1.__importDefault(require("express"));
var bill_1 = tslib_1.__importDefault(require("./routes/bill"));
var default_1 = tslib_1.__importDefault(require("./routes/default"));
var games_1 = tslib_1.__importDefault(require("./routes/games"));
var monitor_1 = tslib_1.__importDefault(require("./routes/monitor"));
var notification_1 = tslib_1.__importDefault(require("./routes/notification"));
var player_1 = tslib_1.__importDefault(require("./routes/player"));
var records_1 = tslib_1.__importDefault(require("./routes/records"));
var rooms_1 = tslib_1.__importDefault(require("./routes/rooms"));
var users_1 = tslib_1.__importDefault(require("./routes/users"));
var video_1 = tslib_1.__importDefault(require("./routes/video"));
var wallet_1 = tslib_1.__importDefault(require("./routes/wallet"));
var customRoute = express_1.default();
customRoute.use("/account", users_1.default);
customRoute.use("/player", player_1.default);
customRoute.use("/games", games_1.default);
customRoute.use("/monitor", monitor_1.default);
customRoute.use("/records", records_1.default);
customRoute.use("/default", default_1.default);
customRoute.use("/rooms", rooms_1.default);
customRoute.use("/video", video_1.default);
customRoute.use("/wallet", wallet_1.default);
customRoute.use("/notifications", notification_1.default);
customRoute.use("/bill", bill_1.default);
exports.default = customRoute;
